const tfData = [
    { question: "Software engineering is only concerned with writing code.", correct: false },
    { question: "Customized software products are designed for a specific customer's needs.", correct: true },
    { question: "Software maintenance is often more expensive than its initial development.", correct: true },
    { question: "Software engineers are not expected to follow any ethical guidelines.", correct: false },
    { question: "Dependability includes attributes like availability, reliability, and security.", correct: true },
    { question: "A system that controls a chemical plant is an example of a mission-critical system.", correct: false },
    { question: "Agile methodology emphasizes long-term planning over iterations.", correct: false },
    { question: "The product owner is responsible for defining requirements in an Agile team.", correct: true },
    { question: "In MVC, the View contains the business logic of the application.", correct: false },
    { question: "Laravel is a PHP framework that follows the MVC design pattern.", correct: true },
    { question: "A good software product must be secure and efficient.", correct: true },
    { question: "In waterfall models, testing is performed before development.", correct: false },
    { question: "The main goal of release testing is to identify as many defects as possible.", correct: false },
    { question: "Unit testing is performed after system testing.", correct: false },
    { question: "Scrum Master is responsible for shielding the Agile team from external disruptions.", correct: true },
    { question: "Fault recovery is part of the fault tolerance strategy.", correct: true },
    { question: "All acceptance criteria must be met for a user story to be considered 'done.'", correct: true },
    { question: "COCOMO is a model used for estimating software costs and effort.", correct: true },
    { question: "Generic software products are developed for a specific client.", correct: false },
    { question: "Web-based systems are generally easier to develop than desktop applications.", correct: false },
    { question: "Software engineers should not misrepresent their level of competence.", correct: true },
    { question: "A cross-functional Agile team includes both technical and non-technical roles.", correct: true },
    { question: "Regression testing is always performed manually.", correct: false },
    { question: "Experience-based validation is used to evaluate security risks.", correct: true },
    { question: "An embedded system in an insulin pump is not safety-critical.", correct: false },
    { question: "Static models use multiple variables for cost estimation.", correct: false },
    { question: "JIRA is a tool used for project management.", correct: true },
    { question: "System testing validates interaction between modules.", correct: true },
    { question: "Model checking is used to ensure consistency between system models.", correct: true },
    { question: "Risk management includes risk identification and quantification.", correct: true },
    { question: "In Agile, user stories are written after development is complete.", correct: false },
    { question: "Product backlog contains functional and non-functional requirements.", correct: true },
    { question: "Formal verification is widely used in software security validation.", correct: false },
    { question: "Velocity in Agile measures the number of releases per month.", correct: false },
    { question: "Interactive transaction-based applications require no internet connection.", correct: false },
    { question: "MHC-PMS is a system used in banking and finance.", correct: false },
    { question: "Partition testing involves selecting test inputs with common characteristics.", correct: true },
    { question: "Test-driven development writes code before writing any test cases.", correct: false },
    { question: "Story points in Agile measure the size or effort required for user stories.", correct: true },
    { question: "The 'Controller' in MVC is responsible for handling user input.", correct: true }
];